### ISSUE TITLE
out of function

### ISSUE THREAD

**Issue by tigranbarseghyan** [M1kayel/my_repo#2]
https://github.com/M1kayel/my_repo/blob/3b5837287ba1e634de2a7e8f05c8737b232453b8/hwbm/hwbm2.py#L86

The logic of the code is out of any function

**Comment by M1kayel** [comment]
Now logic is in function  ,    and also added "top_players" sorting function 

https://github.com/M1kayel/my_repo/blob/main/hwbm/hwbm2.py
